copy-data:
	rm -rf test_dir/input/data
	mkdir -p test_dir/input/data
	cp ../../data/* test_dir/input/data
.PHONY: copy-data

local-train:
	sh train_local.sh fashion-mnist-train:latest
.PHONY: local-train
